team:
  name: "Team"
  base:
    location: "behind Center Camp Cafe"
battle:
  cry: "MAN ALIVE"
flag:
  color: red
  highlight: orange
font:
  family: Arial Black
other_site:
  url: http://ritualwarfare.space
