team:
  name: "Man"
  base:
    location: "behind Center Camp Cafe"
battle:
  cry: "MAN ALIVE"
flag:
  background: black
  color: red
  highlight: orange
font:
  family: Arial Black, Arial
other_site:
  url: http://ritualwarfare.space
